# Install GUI application script
install_data(
    'budgie-radio-browser.py',
    install_dir: get_option('bindir'),
    install_mode: 'rwxr-xr-x',
    rename: 'budgie-radio-browser'
)

# Install desktop file
install_data(
    'budgie-radio-browser.desktop',
    install_dir: join_paths(get_option('datadir'), 'applications')
)
